feat: warn when unused conflicts are present in a grammar
tree-sitter/tree-sitter pull request #2437
Opened 2023-07-27 19:15 UTC by amaanq

Closes #267 

Sample output w/ c++:

![image](https://github.com/tree-sitter/tree-sitter/assets/29718261/5afb8efe-7778-4f4c-8297-536bebd24467)

2023-07-27 19:20 UTC, amaanq commented
I wonder if this is okay as default behavior, we could add a flag if not

2023-07-28 01:29 UTC, ahlinc requested changes

2023-07-28 01:29 UTC, ahlinc commented on cli/src/generate/build_tables/build_parse_table.rs
> +        .collect();
For this place I'd suggest to rewrite it like in the commit: https://github.com/amaanq/tree-sitter/commit/9aa0b08ccd073782256dd0d2948edf0dad21c464

2023-07-28 01:37 UTC, ahlinc commented
I think it's okay to be default behavior because it would lead to less commited errors and if an author during a grammar development would see such warning it would be less of confuse of why added conflicts aren't work.

Visual representation makes sense to improve in a future PR where improve styling for all emitable messages.

2023-07-28 04:59 UTC, merged