fix: disallow tokens that match the empty string
tree-sitter/tree-sitter pull request #2446
Opened 2023-07-31 14:16 UTC by amaanq

This keeps the behavior the same as non-token rules, and prevents an infinite loop bug

Closes #1271

2023-07-31 20:14 UTC, Vicbiger21 commented
Mine

2023-08-01 06:18 UTC, ahlinc requested changes

2023-08-01 06:18 UTC, ahlinc commented on cli/src/generate/prepare_grammar/expand_tokens.rs
> +unless they are used only as the grammar's start rule.
Could you apply `indoc!` here?

2023-08-02 17:45 UTC, amaanq commented on cli/src/generate/prepare_grammar/expand_tokens.rs
> +unless they are used only as the grammar's start rule.
I copied it from `flatten_grammar.rs`

2023-08-02 17:58 UTC, ahlinc commented on cli/src/generate/prepare_grammar/expand_tokens.rs
> +unless they are used only as the grammar's start rule.
Ok, then somehow as a next step.

2024-11-02 04:58 UTC, closed without merging