fix: patch ci
tree-sitter/tree-sitter pull request #3971
Opened 2024-11-29 23:07 UTC by WillLillis

Spent a little time digging into some of the recent issues popping up in CI runs.  I *think* this should fix the two problems I outlined below, but  you never know until you actually do a run. 

To be specific:

- Running  `cargo +nightly test --workspace --all-targets` on nightly gives the following error:

```sh
error: unexpected `cfg` condition value: `used_linker`
Error:   --> cli/src/fuzz/allocations.rs:10:1
   |
10 | #[ctor::ctor]
   | ^^^^^^^^^^^^^
   |
   = note: expected values for `feature` are: `wasm`
   = help: consider adding `used_linker` as a feature in `Cargo.toml`
   = note: see <https://doc.rust-lang.org/nightly/rustc/check-cfg/cargo-specifics.html> for more information about checking conditional configuration
   = note: `-D unexpected-cfgs` implied by `-D warnings`
   = help: to override `-D warnings` add `#[allow(unexpected_cfgs)]`
   = note: this error originates in the attribute macro `ctor::ctor` (in Nightly builds, run with -Z macro-backtrace for more info)

    Checking xtask v0.1.0 (/home/runner/work/tree-sitter/tree-sitter/xtask)
error: unexpected `cfg` condition value: `used_linker`
Error:   --> cli/src/tests/helpers/allocations.rs:10:1
   |
10 | #[ctor::ctor]
   | ^^^^^^^^^^^^^
   |
   = note: expected values for `feature` are: `wasm`
   = help: consider adding `used_linker` as a feature in `Cargo.toml`
   = note: see <https://doc.rust-lang.org/nightly/rustc/check-cfg/cargo-specifics.html> for more information about checking conditional configuration
   = note: this error originates in the attribute macro `ctor::ctor` (in Nightly builds, run with -Z macro-backtrace for more info)

error: could not compile `tree-sitter-cli` (lib) due to 1 previous error
warning: build failed, waiting for other jobs to finish...
error: could not compile `tree-sitter-cli` (lib test) due to 2 previous errors
make: *** [Makefile:108: lint] Error 101
Error: Process completed with exit code 2.
```

This shows up during the `Lint files` step of our `check` workflow. These errors were reported in the rust-ctor crate [here](https://github.com/mmastrac/rust-ctor/issues/309), and patched in the 0.2.9 release. So to fix this I just bumped the dependency version from 0.2.8 to 0.2.9.

- Running ` cargo install cross --git https://github.com/cross-rs/cross` as part of the `Install cross` step of our `build` workflow results in the following errors:

<Details>

```sh
warning: creating a shared reference to mutable static is discouraged
   --> src/docker/local.rs:168:34
    |
168 |     let is_terminated = unsafe { crate::errors::TERMINATED.load(Ordering::SeqCst) };
    |                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ shared reference to mutable static
    |
    = note: for more information, see <https://doc.rust-lang.org/nightly/edition-guide/rust-2024/static-mut-references.html>
    = note: shared references to mutable statics are dangerous; it's undefined behavior if the static is mutated or if a mutable reference is created for it while the shared reference lives
    = note: `#[warn(static_mut_refs)]` on by default

warning: creating a shared reference to mutable static is discouraged
   --> src/docker/shared.rs:568:17
    |
568 |             if !CHILD_CONTAINER.exists.swap(true, Ordering::SeqCst) {
    |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ shared reference to mutable static
    |
    = note: for more information, see <https://doc.rust-lang.org/nightly/edition-guide/rust-2024/static-mut-references.html>
    = note: shared references to mutable statics are dangerous; it's undefined behavior if the static is mutated or if a mutable reference is created for it while the shared reference lives

warning: creating a shared reference to mutable static is discouraged
   --> src/docker/shared.rs:592:18
    |
592 |         unsafe { CHILD_CONTAINER.exists() }
    |                  ^^^^^^^^^^^^^^^^^^^^^^^^ shared reference to mutable static
    |
    = note: for more information, see <https://doc.rust-lang.org/nightly/edition-guide/rust-2024/static-mut-references.html>
    = note: shared references to mutable statics are dangerous; it's undefined behavior if the static is mutated or if a mutable reference is created for it while the shared reference lives

warning: creating a mutable reference to mutable static is discouraged
   --> src/docker/shared.rs:604:13
    |
604 |             CHILD_CONTAINER.exit();
    |             ^^^^^^^^^^^^^^^^^^^^^^ mutable reference to mutable static
    |
    = note: for more information, see <https://doc.rust-lang.org/nightly/edition-guide/rust-2024/static-mut-references.html>
    = note: mutable references to mutable statics are dangerous; it's undefined behavior if any other pointer to the static is used or if any other reference is created for the static while the mutable reference lives

warning: creating a mutable reference to mutable static is discouraged
   --> src/docker/shared.rs:630:13
    |
630 |             CHILD_CONTAINER.finish(is_tty, msg_info);
    |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ mutable reference to mutable static
    |
    = note: for more information, see <https://doc.rust-lang.org/nightly/edition-guide/rust-2024/static-mut-references.html>
    = note: mutable references to mutable statics are dangerous; it's undefined behavior if any other pointer to the static is used or if any other reference is created for the static while the mutable reference lives

warning: creating a shared reference to mutable static is discouraged
  --> src/errors.rs:27:9
   |
27 |     if !TERMINATED.swap(true, Ordering::SeqCst) && temp::has_tempfiles() {
   |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ shared reference to mutable static
   |
   = note: for more information, see <https://doc.rust-lang.org/nightly/edition-guide/rust-2024/static-mut-references.html>
   = note: shared references to mutable statics are dangerous; it's undefined behavior if the static is mutated or if a mutable reference is created for it while the shared reference lives

warning: creating a mutable reference to mutable static is discouraged
   --> src/errors.rs:105:5
    |
105 |     docker::CHILD_CONTAINER.terminate();
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ mutable reference to mutable static
    |
    = note: for more information, see <https://doc.rust-lang.org/nightly/edition-guide/rust-2024/static-mut-references.html>
    = note: mutable references to mutable statics are dangerous; it's undefined behavior if any other pointer to the static is used or if any other reference is created for the static while the mutable reference lives

warning: creating a shared reference to mutable static is discouraged
  --> src/temp.rs:22:15
   |
22 |     unsafe { !FILES.is_empty() || !DIRS.is_empty() }
   |               ^^^^^^^^^^^^^^^^ shared reference to mutable static
   |
   = note: for more information, see <https://doc.rust-lang.org/nightly/edition-guide/rust-2024/static-mut-references.html>
   = note: shared references to mutable statics are dangerous; it's undefined behavior if the static is mutated or if a mutable reference is created for it while the shared reference lives

warning: creating a shared reference to mutable static is discouraged
  --> src/temp.rs:22:36
   |
22 |     unsafe { !FILES.is_empty() || !DIRS.is_empty() }
   |                                    ^^^^^^^^^^^^^^^ shared reference to mutable static
   |
   = note: for more information, see <https://doc.rust-lang.org/nightly/edition-guide/rust-2024/static-mut-references.html>
   = note: shared references to mutable statics are dangerous; it's undefined behavior if the static is mutated or if a mutable reference is created for it while the shared reference lives

warning: creating a mutable reference to mutable static is discouraged
  --> src/temp.rs:31:5
   |
31 |     FILES.clear();
   |     ^^^^^^^^^^^^^ mutable reference to mutable static
   |
   = note: for more information, see <https [...]

2024-11-29 23:16 UTC, amaanq requested changes
Why not just allow `static_mut_refs` in our clippy config in Cargo.toml in the meantime for the cross issue?

2024-11-29 23:17 UTC, WillLillis commented
> Why not just allow `static_mut_refs` in our clippy config in Cargo.toml in the meantime for the cross issue?

No particular reason, I'll use that instead

2024-11-29 23:23 UTC, amaanq approved these changes
nice, thank you

2024-11-29 23:27 UTC, WillLillis commented
Actually, checking the latest run it looks like lints marked as allowed in `Cargo.toml` aren't considered when installing cross. Am I missing something there?

2024-11-29 23:40 UTC, amaanq commented
Ah wait you're right - you can override the flags when installing cross then, my bad

2024-11-30 00:15 UTC, WillLillis commented
Not sure about the wasmtime library failures, I can take another look later tonight.

2024-11-30 08:12 UTC, ObserverOfTime commented on .github/workflows/build.yml
> +        mkdir target
```suggestion
        mkdir -p target
```

2024-12-03 21:41 UTC, merged